### ISSUE TITLE
make slides update

### ISSUE THREAD

**Issue by jenrichmond** [jenrichmond/AIMOSworkshop#6]
making good progress on slides, have pushed updates to git, but when I check out the slides from the  landing page https://jenrichmond.github.io/AIMOSworkshop/ they are old.... how to make them update? something about "building" the site again??

xx J

**Comment by softloud** [comment]
Am still figuring this out myself, so apologies if instructions send you awry:

From my blog, I think yup, we need to rebuild the website. 

Try opening index.Rmd and hitting **ctl + shit + B**.

Another option is to `xaringan::inf_mr`; that seems to rebuild everything, too. I usually go with that, because as soon as I start inspecting, I start finding typos. 

And *then* you need to 

```
git add .
git commit -m "update site message"
git push
```
in order to get it onto github pages.

Fair warning, it takes a few _agonisingly_ **interminable** minutes between pushing and github pages updating.
